### ISSUE TITLE
Finer grained types to drive the generators

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar-spec#133]
### Category

DRT generator(s)

### Describe the feature you'd like to request

The types to drive the generators are coarse grained. For instance, there's only one record type and one entity type. It has at least two drawbacks.

1. It's harder to generate policies that can be validated. For instance, well typed sets of entities should contain entities of the same entity types.
2. It leads to missing coverage (e.g., #132).

### Describe alternatives you've considered

We should survey literatures on type-driven expression generations and see if we can derive the generator from the type checker.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by mwhicks1** [comment]
Not sure what you mean by this.

Note that there is the "type directed" generator, but also the "schema type" directed one. The latter is a particular Cedar type. TBH, I think we should drop the former in favor of just using the latter.

**Comment by shaobo-he-aws** [comment]
Closed as it's not relevant.
