### ISSUE TITLE
Compare number of errors in authorization targets

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar-spec#188]
### Category

DRT infrastructure

### Describe the feature you'd like to request

Currently, the DRT does not compare errors in authorization targets, only the Allow/Deny decision and the list of determining policies.  We should also compare that the implementations agree on which policies produced errors (even if we don't specify the content of those errors).

### Describe alternatives you've considered

Evaluation targets already check that for any given expression, the implementations agree whether an error was produced or not.  We could decide that is sufficient, and we don't need to check errors in authorization targets.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Resolved (for the Lean implementation) by #206 and #208
