### ISSUE TITLE
Check `assume`s or axioms in Dafny files in CI

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar-spec#65]
### Category

Other

### Describe the feature you'd like to request

We should grep keywords that could lead to assumptions in Dafny proofs. This should prevent us from, e.g., accidentally merging unfinished proofs.

### Describe the solution you'd like

Grep assume or axiom in all Dafny files.

### Describe alternatives you've considered

Maybe there's a Dafny flag we can leverage.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
https://dafny.org/dafny/DafnyRef/DafnyRef#sec-dafny-audit

Should be as easy as adding `dafny audit` to CI

**Comment by khieta** [comment]
Marking this as done since #72 was merged.
