### ISSUE TITLE
Finer-grained answer comparison

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar-spec#69]
### Category

Other

### Describe the feature you'd like to request

Currently, DRT performs a coarse-grained authorization author comparison between Rust and Dafny. In other words, we throw away diagnostic like runtime errors and only compare the verdicts (along with the policies that lead to them).

### Describe the solution you'd like

We should implementation a much stronger equality test to take these info into account.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Addressed in #206 and #208 (for Lean), and we decided to only compare erroring policy IDs not actual error content, as a matter of policy.  Closing this as completed.
